import logo1 from '../Assets/images2/logo1.png'
import logo2 from '../Assets/images2/logo2.png'
import logo3 from '../Assets/images2/logo3.png'
import logo4 from '../Assets/images2/logo4.png'
import logo5 from '../Assets/images2/logo5.png'