//dev:  ABI- EVCNFT  Data
export const abiEVCNFT = [{
  "inputs": [{
      "internalType": "string",
      "name": "_name",
      "type": "string"
  }, {
      "internalType": "string",
      "name": "_symbol",
      "type": "string"
  }],
  "stateMutability": "nonpayable",
  "type": "constructor"
}, {
  "anonymous": false,
  "inputs": [{
      "indexed": true,
      "internalType": "address",
      "name": "owner",
      "type": "address"
  }, {
      "indexed": true,
      "internalType": "address",
      "name": "approved",
      "type": "address"
  }, {
      "indexed": true,
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }],
  "name": "Approval",
  "type": "event"
}, {
  "anonymous": false,
  "inputs": [{
      "indexed": true,
      "internalType": "address",
      "name": "owner",
      "type": "address"
  }, {
      "indexed": true,
      "internalType": "address",
      "name": "operator",
      "type": "address"
  }, {
      "indexed": false,
      "internalType": "bool",
      "name": "approved",
      "type": "bool"
  }],
  "name": "ApprovalForAll",
  "type": "event"
}, {
  "anonymous": false,
  "inputs": [{
      "indexed": true,
      "internalType": "address",
      "name": "previousOwner",
      "type": "address"
  }, {
      "indexed": true,
      "internalType": "address",
      "name": "newOwner",
      "type": "address"
  }],
  "name": "OwnershipTransferred",
  "type": "event"
}, {
  "anonymous": false,
  "inputs": [{
      "indexed": true,
      "internalType": "address",
      "name": "from",
      "type": "address"
  }, {
      "indexed": true,
      "internalType": "address",
      "name": "to",
      "type": "address"
  }, {
      "indexed": true,
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }],
  "name": "Transfer",
  "type": "event"
}, {
  "stateMutability": "payable",
  "type": "fallback"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "_percentage",
      "type": "uint256"
  }, {
      "internalType": "uint256",
      "name": "_mintAmount",
      "type": "uint256"
  }],
  "name": "adminBuyAndBurnPercentage",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "to",
      "type": "address"
  }, {
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }],
  "name": "approve",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "owner",
      "type": "address"
  }],
  "name": "balanceOf",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [],
  "name": "baseExtension",
  "outputs": [{
      "internalType": "string",
      "name": "",
      "type": "string"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [],
  "name": "baseURI",
  "outputs": [{
      "internalType": "string",
      "name": "",
      "type": "string"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "percentage",
      "type": "uint256"
  }, {
      "internalType": "uint256",
      "name": "mintAmount",
      "type": "uint256"
  }],
  "name": "buyandBurnPercentage",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_ref",
      "type": "address"
  }, {
      "internalType": "address[]",
      "name": "to",
      "type": "address[]"
  }],
  "name": "createReferralArray",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "name": "evcSwapVestByUser",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }],
  "name": "getApproved",
  "outputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "referrer",
      "type": "address"
  }],
  "name": "getDirectReferrals",
  "outputs": [{
      "internalType": "address[]",
      "name": "",
      "type": "address[]"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "_level",
      "type": "uint256"
  }],
  "name": "getNFTCost",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "account",
      "type": "address"
  }],
  "name": "getRecentlyJoinedTeamMembers",
  "outputs": [{
      "internalType": "address[]",
      "name": "",
      "type": "address[]"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_user",
      "type": "address"
  }],
  "name": "getReferrerOf",
  "outputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "user",
      "type": "address"
  }],
  "name": "getShareUniReward",
  "outputs": [{
      "components": [{
          "internalType": "address[]",
          "name": "users",
          "type": "address[]"
      }, {
          "internalType": "uint256",
          "name": "percentage",
          "type": "uint256"
      }, {
          "internalType": "bool",
          "name": "agreed",
          "type": "bool"
      }],
      "internalType": "struct Avtars.ShareUniReward",
      "name": "",
      "type": "tuple"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "user",
      "type": "address"
  }],
  "name": "getTotalPartners",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_user",
      "type": "address"
  }],
  "name": "getUnilevelReferrer",
  "outputs": [{
      "components": [{
          "internalType": "address",
          "name": "referrer",
          "type": "address"
      }, {
          "internalType": "uint256",
          "name": "percentage",
          "type": "uint256"
      }],
      "internalType": "struct Avtars.UnilevelPrecentage[]",
      "name": "",
      "type": "tuple[]"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }, {
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "name": "hasNFTs",
  "outputs": [{
      "internalType": "bool",
      "name": "",
      "type": "bool"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_usdc",
      "type": "address"
  }, {
      "internalType": "address",
      "name": "_evc",
      "type": "address"
  }, {
      "internalType": "address",
      "name": "_evcRouter",
      "type": "address"
  }, {
      "internalType": "address",
      "name": "_vest",
      "type": "address"
  }],
  "name": "initialize",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "owner",
      "type": "address"
  }, {
      "internalType": "address",
      "name": "operator",
      "type": "address"
  }],
  "name": "isApprovedForAll",
  "outputs": [{
      "internalType": "bool",
      "name": "",
      "type": "bool"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "name": "isWhitelisted",
  "outputs": [{
      "internalType": "bool",
      "name": "",
      "type": "bool"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "_level",
      "type": "uint256"
  }, {
      "internalType": "uint256",
      "name": "_mintPrice",
      "type": "uint256"
  }, {
      "internalType": "bool",
      "name": "_delegate",
      "type": "bool"
  }, {
      "internalType": "address",
      "name": "_referrer",
      "type": "address"
  }],
  "name": "mintNFT",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "_level",
      "type": "uint256"
  }, {
      "internalType": "uint256",
      "name": "_mintPrice",
      "type": "uint256"
  }, {
      "internalType": "bool",
      "name": "_delegate",
      "type": "bool"
  }, {
      "internalType": "address",
      "name": "_referrer",
      "type": "address"
  }, {
      "internalType": "address[]",
      "name": "rbmembers",
      "type": "address[]"
  }, {
      "internalType": "uint256[]",
      "name": "rbpercentages",
      "type": "uint256[]"
  }],
  "name": "mintNFT1",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [],
  "name": "name",
  "outputs": [{
      "internalType": "string",
      "name": "",
      "type": "string"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [],
  "name": "owner",
  "outputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }],
  "name": "ownerOf",
  "outputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "bool",
      "name": "_state",
      "type": "bool"
  }],
  "name": "pause",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [],
  "name": "paused",
  "outputs": [{
      "internalType": "bool",
      "name": "",
      "type": "bool"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "name": "rankBonusEarningsByUser",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_user",
      "type": "address"
  }],
  "name": "removeWhitelistUser",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [],
  "name": "renounceOwnership",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "from",
      "type": "address"
  }, {
      "internalType": "address",
      "name": "to",
      "type": "address"
  }, {
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }],
  "name": "safeTransferFrom",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "from",
      "type": "address"
  }, {
      "internalType": "address",
      "name": "to",
      "type": "address"
  }, {
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }, {
      "internalType": "bytes",
      "name": "data",
      "type": "bytes"
  }],
  "name": "safeTransferFrom",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "to",
      "type": "address"
  }, {
      "internalType": "uint256",
      "name": "amount",
      "type": "uint256"
  }],
  "name": "setApproval",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "operator",
      "type": "address"
  }, {
      "internalType": "bool",
      "name": "approved",
      "type": "bool"
  }],
  "name": "setApprovalForAll",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "string",
      "name": "_newBaseExtension",
      "type": "string"
  }],
  "name": "setBaseExtension",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "string",
      "name": "_baseURI",
      "type": "string"
  }],
  "name": "setBaseURI",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_newDelegateAddress",
      "type": "address"
  }],
  "name": "setDelegate",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_newEVCRouterAdress",
      "type": "address"
  }],
  "name": "setEVCRouterAdress",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256[]",
      "name": "newCosts",
      "type": "uint256[]"
  }],
  "name": "setNFTCosts",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_userAddress",
      "type": "address"
  }, {
      "internalType": "uint256",
      "name": "_level",
      "type": "uint256"
  }],
  "name": "setNFTLevel",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "from",
      "type": "address"
  }, {
      "internalType": "address[]",
      "name": "users",
      "type": "address[]"
  }, {
      "internalType": "uint256",
      "name": "percentage",
      "type": "uint256"
  }, {
      "internalType": "bool",
      "name": "status",
      "type": "bool"
  }],
  "name": "setShareUniLevelReward",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_newtoken0",
      "type": "address"
  }],
  "name": "setToken0",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_newtoken1",
      "type": "address"
  }],
  "name": "setToken1",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "_totalPaidUniLevelRewards",
      "type": "uint256"
  }],
  "name": "setTotalPaidUniLevelRewards",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_newUSDCToken",
      "type": "address"
  }],
  "name": "setUSDCToken",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_vestContract",
      "type": "address"
  }],
  "name": "setVestContract",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "name": "shareUniReward",
  "outputs": [{
      "internalType": "uint256",
      "name": "percentage",
      "type": "uint256"
  }, {
      "internalType": "bool",
      "name": "agreed",
      "type": "bool"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "bytes4",
      "name": "interfaceId",
      "type": "bytes4"
  }],
  "name": "supportsInterface",
  "outputs": [{
      "internalType": "bool",
      "name": "",
      "type": "bool"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [],
  "name": "symbol",
  "outputs": [{
      "internalType": "string",
      "name": "",
      "type": "string"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "index",
      "type": "uint256"
  }],
  "name": "tokenByIndex",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "owner",
      "type": "address"
  }, {
      "internalType": "uint256",
      "name": "index",
      "type": "uint256"
  }],
  "name": "tokenOfOwnerByIndex",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }],
  "name": "tokenURI",
  "outputs": [{
      "internalType": "string",
      "name": "",
      "type": "string"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [],
  "name": "totalPaidUniLevelRewards",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [],
  "name": "totalSupply",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "uint256",
      "name": "_level",
      "type": "uint256"
  }],
  "name": "totalSupplyOfLevel",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "from",
      "type": "address"
  }, {
      "internalType": "address",
      "name": "to",
      "type": "address"
  }, {
      "internalType": "uint256",
      "name": "tokenId",
      "type": "uint256"
  }],
  "name": "transferFrom",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "newOwner",
      "type": "address"
  }],
  "name": "transferOwnership",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "",
      "type": "address"
  }],
  "name": "unilevelEarningsByUser",
  "outputs": [{
      "internalType": "uint256",
      "name": "",
      "type": "uint256"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_user",
      "type": "address"
  }, {
      "internalType": "uint256",
      "name": "_amount",
      "type": "uint256"
  }],
  "name": "unilevelReward",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address[]",
      "name": "recipients",
      "type": "address[]"
  }, {
      "internalType": "uint256[]",
      "name": "RBpercentages",
      "type": "uint256[]"
  }, {
      "internalType": "uint256",
      "name": "mintAmount",
      "type": "uint256"
  }],
  "name": "usdcAndEvcRankBonus",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_owner",
      "type": "address"
  }],
  "name": "walletOfOwner",
  "outputs": [{
      "internalType": "uint256[]",
      "name": "",
      "type": "uint256[]"
  }],
  "stateMutability": "view",
  "type": "function"
}, {
  "inputs": [{
      "internalType": "address",
      "name": "_user",
      "type": "address"
  }],
  "name": "whitelistUser",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}, {
  "inputs": [],
  "name": "withdraw",
  "outputs": [],
  "stateMutability": "payable",
  "type": "function"
}, {
  "stateMutability": "payable",
  "type": "receive"
}]