// //dev: ABI- abiLocker data
// export const abiLocker = [{
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }, {
//         "internalType": "address",
//         "name": "_token1",
//         "type": "address"
//     }, {
//         "internalType": "address",
//         "name": "_token2",
//         "type": "address"
//     }],
//     "stateMutability": "nonpayable",
//     "type": "constructor"
// }, {
//     "anonymous": false,
//     "inputs": [{
//         "indexed": true,
//         "internalType": "address",
//         "name": "previousOwner",
//         "type": "address"
//     }, {
//         "indexed": true,
//         "internalType": "address",
//         "name": "newOwner",
//         "type": "address"
//     }],
//     "name": "OwnershipTransferred",
//     "type": "event"
// }, {
//     "anonymous": false,
//     "inputs": [{
//         "indexed": false,
//         "internalType": "address",
//         "name": "pairAddress",
//         "type": "address"
//     }, {
//         "indexed": true,
//         "internalType": "address",
//         "name": "locker",
//         "type": "address"
//     }, {
//         "indexed": true,
//         "internalType": "address",
//         "name": "owner",
//         "type": "address"
//     }, {
//         "indexed": false,
//         "internalType": "uint256",
//         "name": "amount",
//         "type": "uint256"
//     }, {
//         "indexed": false,
//         "internalType": "uint256",
//         "name": "unlockTime",
//         "type": "uint256"
//     }, {
//         "indexed": false,
//         "internalType": "uint256",
//         "name": "lockID",
//         "type": "uint256"
//     }],
//     "name": "liquidityLocked",
//     "type": "event"
// }, {
//     "anonymous": false,
//     "inputs": [{
//         "indexed": false,
//         "internalType": "address",
//         "name": "pairAddress",
//         "type": "address"
//     }, {
//         "indexed": true,
//         "internalType": "address",
//         "name": "oldOwner",
//         "type": "address"
//     }, {
//         "indexed": true,
//         "internalType": "address",
//         "name": "newOwner",
//         "type": "address"
//     }, {
//         "indexed": false,
//         "internalType": "uint256",
//         "name": "lockID",
//         "type": "uint256"
//     }],
//     "name": "liquidityMigrated",
//     "type": "event"
// }, {
//     "anonymous": false,
//     "inputs": [{
//         "indexed": false,
//         "internalType": "address",
//         "name": "pairAddress",
//         "type": "address"
//     }, {
//         "indexed": true,
//         "internalType": "address",
//         "name": "reciever",
//         "type": "address"
//     }, {
//         "indexed": false,
//         "internalType": "uint256",
//         "name": "amount",
//         "type": "uint256"
//     }, {
//         "indexed": false,
//         "internalType": "uint256",
//         "name": "lockID",
//         "type": "uint256"
//     }],
//     "name": "liquidityUnLocked",
//     "type": "event"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "name": "LPtokens",
//     "outputs": [{
//         "internalType": "address",
//         "name": "LPAddress",
//         "type": "address"
//     }, {
//         "internalType": "address",
//         "name": "token1",
//         "type": "address"
//     }, {
//         "internalType": "address",
//         "name": "token2",
//         "type": "address"
//     }, {
//         "internalType": "uint256",
//         "name": "totalValueLocked",
//         "type": "uint256"
//     }, {
//         "internalType": "uint256",
//         "name": "lockBalance",
//         "type": "uint256"
//     }, {
//         "internalType": "uint256",
//         "name": "totalLocks",
//         "type": "uint256"
//     }, {
//         "internalType": "uint256",
//         "name": "totalActiveLocks",
//         "type": "uint256"
//     }, {
//         "internalType": "uint256",
//         "name": "isActive",
//         "type": "uint256"
//     }, {
//         "internalType": "uint256",
//         "name": "islocked",
//         "type": "uint256"
//     }, {
//         "internalType": "bool",
//         "name": "isSet",
//         "type": "bool"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "SwapRouter",
//     "outputs": [{
//         "internalType": "contract IPancakeV2Router02",
//         "name": "",
//         "type": "address"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "name": "_ExcludedFromFee",
//     "outputs": [{
//         "internalType": "bool",
//         "name": "",
//         "type": "bool"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "feeBalance",
//     "outputs": [{
//         "internalType": "uint256",
//         "name": "",
//         "type": "uint256"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "fees",
//     "outputs": [{
//         "internalType": "uint256",
//         "name": "",
//         "type": "uint256"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }],
//     "name": "getActiveLPLockIDs",
//     "outputs": [{
//         "internalType": "uint256[]",
//         "name": "",
//         "type": "uint256[]"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }, {
//         "internalType": "uint256",
//         "name": "lockID",
//         "type": "uint256"
//     }],
//     "name": "getLPLock",
//     "outputs": [{
//         "components": [{
//             "internalType": "uint256",
//             "name": "amount",
//             "type": "uint256"
//         }, {
//             "internalType": "address",
//             "name": "reciever",
//             "type": "address"
//         }, {
//             "internalType": "uint256",
//             "name": "unlockTime",
//             "type": "uint256"
//         }, {
//             "internalType": "bool",
//             "name": "isActive",
//             "type": "bool"
//         }, {
//             "internalType": "bool",
//             "name": "isSet",
//             "type": "bool"
//         }],
//         "internalType": "struct liquidityTimeLock.lpLock",
//         "name": "",
//         "type": "tuple"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "user",
//         "type": "address"
//     }, {
//         "internalType": "uint256",
//         "name": "lockId",
//         "type": "uint256"
//     }],
//     "name": "getLockInfo",
//     "outputs": [{
//         "internalType": "uint256",
//         "name": "",
//         "type": "uint256"
//     }, {
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }, {
//         "internalType": "uint256",
//         "name": "",
//         "type": "uint256"
//     }, {
//         "internalType": "bool",
//         "name": "",
//         "type": "bool"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_token1",
//         "type": "address"
//     }, {
//         "internalType": "address",
//         "name": "_token2",
//         "type": "address"
//     }],
//     "name": "getPairAddress",
//     "outputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }],
//     "name": "getTokens",
//     "outputs": [{
//         "internalType": "address",
//         "name": "_token1",
//         "type": "address"
//     }, {
//         "internalType": "address",
//         "name": "_token2",
//         "type": "address"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }],
//     "name": "getTotalLocksBalance",
//     "outputs": [{
//         "internalType": "uint256",
//         "name": "",
//         "type": "uint256"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }],
//     "name": "getTotalLocksValue",
//     "outputs": [{
//         "internalType": "uint256",
//         "name": "",
//         "type": "uint256"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "getUserLPlocksAddress",
//     "outputs": [{
//         "internalType": "address[]",
//         "name": "",
//         "type": "address[]"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "name": "isAdmin",
//     "outputs": [{
//         "internalType": "bool",
//         "name": "",
//         "type": "bool"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "uint256",
//         "name": "amount",
//         "type": "uint256"
//     }, {
//         "internalType": "uint256",
//         "name": "periodInSeconds",
//         "type": "uint256"
//     }, {
//         "internalType": "address",
//         "name": "_reciever",
//         "type": "address"
//     }],
//     "name": "lockLiquidity",
//     "outputs": [],
//     "stateMutability": "payable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }, {
//         "internalType": "uint256",
//         "name": "lockID",
//         "type": "uint256"
//     }, {
//         "internalType": "address",
//         "name": "to",
//         "type": "address"
//     }],
//     "name": "migrateLiquidity",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "minLockTimeInSeconds",
//     "outputs": [{
//         "internalType": "uint256",
//         "name": "",
//         "type": "uint256"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "owner",
//     "outputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "pairAddress",
//     "outputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "renounceOwnership",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_admin",
//         "type": "address"
//     }, {
//         "internalType": "bool",
//         "name": "_isAdmin",
//         "type": "bool"
//     }],
//     "name": "setAdmin",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "account",
//         "type": "address"
//     }, {
//         "internalType": "bool",
//         "name": "_exclude",
//         "type": "bool"
//     }],
//     "name": "setExcludeFromFees",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address payable",
//         "name": "_feeAddress",
//         "type": "address"
//     }],
//     "name": "setFeeAddress",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "uint256",
//         "name": "_fees",
//         "type": "uint256"
//     }],
//     "name": "setFees",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }],
//     "name": "setPairAddress",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_token1",
//         "type": "address"
//     }],
//     "name": "setToken1",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_token2",
//         "type": "address"
//     }],
//     "name": "setToken2",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "uint256",
//         "name": "_minLockTimeInSeconds",
//         "type": "uint256"
//     }],
//     "name": "setminLockTimeInSeconds",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "token1",
//     "outputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "token2",
//     "outputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "newOwner",
//         "type": "address"
//     }],
//     "name": "transferOwnership",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_pairAddress",
//         "type": "address"
//     }, {
//         "internalType": "uint256",
//         "name": "lockID",
//         "type": "uint256"
//     }],
//     "name": "unLockLiquidity",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_router",
//         "type": "address"
//     }],
//     "name": "updateSwapRouter",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "_user",
//         "type": "address"
//     }],
//     "name": "userActiveLocksids",
//     "outputs": [{
//         "internalType": "uint256[]",
//         "name": "",
//         "type": "uint256[]"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [{
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }, {
//         "internalType": "address",
//         "name": "",
//         "type": "address"
//     }],
//     "name": "userLPlocks",
//     "outputs": [{
//         "internalType": "address",
//         "name": "LPAddress",
//         "type": "address"
//     }, {
//         "internalType": "uint256",
//         "name": "locks",
//         "type": "uint256"
//     }, {
//         "internalType": "uint256",
//         "name": "totalValueLocked",
//         "type": "uint256"
//     }, {
//         "internalType": "uint256",
//         "name": "lockBalance",
//         "type": "uint256"
//     }],
//     "stateMutability": "view",
//     "type": "function"
// }, {
//     "inputs": [],
//     "name": "withdrawFees",
//     "outputs": [],
//     "stateMutability": "nonpayable",
//     "type": "function"
// }]